run:
  deadline: 120s
linters:
  enable:
    - misspell
    - stylecheck
    - gocritic
    - unparam
    - unconvert
    - whitespace
    - makezero
  disable:
    - errcheck
linters-settings:
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks:
    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust
      - appendAssign
      - exitAfterDefer
      - ifElseChain
